spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ggmdb
    url: jdbc:mysql://ggmdb.c2rnm9avjkap.ap-northeast-2.rds.amazonaws.com:3306/ggmDB
    password: tnltmxpak
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.example.kkm_back.Domain
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'

cloud:
  aws:
    credentials:
      access-key: AKIAYQITP6EKNETYVJ4U
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: kkm
    stack:
      auto: false

debug: 'true'
server:
  port: '3030'
